string	device_type			# model name
int16 	id					# motor id
string 	device_state		# motor state
string 	operating_mode		# motor operating mode
string	error_code			# motor error code
float32 voltage				# motor voltage (V)
float32 current				# motor voltage (A)
float32 torque				# motor torque (Nm)
float32 cmd_velocity		# motor velocity command (mm/s or rad/s)
float32 fb_velocity			# motor velocity feedback (mm/s or rad/s)
float32 cmd_position		# motor position command (pulse or PUU)
float32 fb_position			# motor position feedback (pulse or PUU)